# Generated by Django 4.0.5 on 2022-08-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_photo_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fishing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(db_index=True, max_length=200, verbose_name='Долгота')),
                ('longitude', models.FloatField(db_index=True, max_length=200, verbose_name='Широта')),
                ('trophies', models.CharField(db_index=True, max_length=100, verbose_name='Трофей')),
                ('description', models.CharField(db_index=True, max_length=255, verbose_name='Описание места')),
                ('publication_date', models.DateTimeField(verbose_name='Дата публикации')),
                ('tackle', models.CharField(db_index=True, max_length=255, verbose_name='Снасти')),
                ('bait', models.CharField(db_index=True, max_length=255, verbose_name='Наживки')),
                ('boat', models.CharField(db_index=True, max_length=255, verbose_name='Лодка')),
                ('motor', models.CharField(db_index=True, max_length=255, verbose_name='Мотор')),
            ],
        ),
        migrations.AlterField(
            model_name='photo',
            name='path',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.DeleteModel(
            name='MapEntity',
        ),
        migrations.AddField(
            model_name='fishing',
            name='photos',
            field=models.ManyToManyField(related_name='photos', to='main.photo'),
        ),
    ]
