# Generated by Django 4.0.5 on 2022-08-25 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_fishing_alter_photo_path_delete_mapentity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishing',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fishing',
            name='bait',
            field=models.CharField(max_length=255, verbose_name='Наживки'),
        ),
        migrations.AlterField(
            model_name='fishing',
            name='boat',
            field=models.CharField(max_length=255, verbose_name='Лодка'),
        ),
        migrations.AlterField(
            model_name='fishing',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Описание места'),
        ),
        migrations.AlterField(
            model_name='fishing',
            name='latitude',
            field=models.FloatField(max_length=200, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='fishing',
            name='longitude',
            field=models.FloatField(max_length=200, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='fishing',
            name='motor',
            field=models.CharField(max_length=255, verbose_name='Мотор'),
        ),
        migrations.AlterField(
            model_name='fishing',
            name='tackle',
            field=models.CharField(max_length=255, verbose_name='Снасти'),
        ),
        migrations.AlterField(
            model_name='fishing',
            name='trophies',
            field=models.CharField(max_length=100, verbose_name='Трофей'),
        ),
    ]
